title:            
description:      
url:              # Site url.
signoff:          Aninha Lacerda
disqus_shortname: aninhalacerda
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-52272080-3

links:
  - name:         About
    url:          /about
    image:        yoga_red.png
  - name:         Talks
    url:          /talks
    image:        talk_red.png
  #- name:         Blog
    #url:          /blog
    #image:        blog_red.png
  #- name:         Email
    #url:          mailto:anaclara.lacerdas@gmail.com
    #image:        mail_red.png
    #external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  hard_wrap: false 
