title:            
description:      
url:              # Site url.
signoff:          Aninha Lacerda
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
    image:        yoga_red.png
  - name:         Blog
    url:          /blog
    image:        blog_red.png
  - name:         Email
    url:          mailto:anaclara.lacerdas@gmail.com
    image:        mail_red.png
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
